[server]
  serverName = "zhyu"
  port = "9090"
  runMode = "debug" # release debug
  logLevel = "debug" # debug info warn error
  logPath = "runtime/logs" # path 日志文件路径
  readTimeout = 30 # 读超时 秒
  writeTimeout = 30 # 写超时 秒
  shutdownTime = 1 # 优雅停止程序 秒
  workerID = 1 # 雪花算法分布式的当前 workerID
  JwtSecret = "c58c3baeb4483b9255013bec45678bd6" # JWT 密钥  zhyu-go-1659263420

[database]
  [database.a]
    host = "localhost"
    port = "3306"
    username = "root"
    password = ""
    dbname = "test"
    max_idle_conn = 10
    max_open_conn = 30
    conn_max_lifetime = 300
  [database.b]
    host = "localhost"
    port = "3306"
    username = "root"
    password = ""
    dbname = "test"
    max_idle_conn = 10
    max_open_conn = 30
    conn_max_lifetime = 300

[redis]
  host = "localhost"
  port = "6379"
  password = ""
  db = 0
  poolSize = 100

[elastic]
  host = "http://127.0.0.1:9200/"
  user = "elastic"
  password = "password"

[ipWhite]
  ip = ["::1", "127.0.0.1"]